TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += dbExample1.db
DB += dbExample2.db
DB += dbSubExample.db
DB += user.substitutions
DB += DLCpro.db
DB += DLCpro.proto
DB += FLM0151.db
DB += FLM0151.proto
DB += AFG3000Channel-internal.template
DB += AFG3000Channel-single.template
DB += AFG3000Channel.template
DB += AFG3000Device.template


# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

